/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package generardordepoblacion;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author cetecom
 */
public class GeneradorDePoblacion extends javax.swing.JFrame {

    ArrayList<String> ruts= new ArrayList<>();
    ArrayList<String> id_productos= new ArrayList<>();
    ArrayList<Productos> productosL= new ArrayList<Productos>();
    public GeneradorDePoblacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        bntVentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();
        btnGuardarScript = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Generador automatico de datos");

        btnUsuarios.setText("Crear Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnProductos.setText("Crear Podructos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        bntVentas.setText("Crear Ventas");
        bntVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVentasActionPerformed(evt);
            }
        });

        txtDatos.setColumns(20);
        txtDatos.setRows(5);
        jScrollPane1.setViewportView(txtDatos);

        btnGuardarScript.setText("Salvar Script");
        btnGuardarScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarScriptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Esperando resultados..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarScript)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUsuarios)
                        .addGap(145, 145, 145)
                        .addComponent(btnProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(bntVentas)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios)
                    .addComponent(btnProductos)
                    .addComponent(bntVentas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarScript)
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        
        
        Clientes clientes= new Clientes();
        for (int i = 0; i < 5; i++) {
              clientes=clientes.generarUsuario(ruts);
              ruts.add(clientes.getRut());
              txtDatos.setText(txtDatos.getText()+"\n"+clientes.toString());
        }
      
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
       Productos productos= new Productos();
        for (int i = 0; i < 30; i++) {
              productos=productos.generarProductos();
              id_productos.add(productos.getId());
              productosL.add(productos);
              txtDatos.setText(txtDatos.getText()+"\n"+productos.toString());
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void bntVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVentasActionPerformed
        
        try{
        Ventas ventas= new Ventas();
        ProductosVendidos productosVendidos= new ProductosVendidos();
        
        for (int i = 0; i < 60; i++) {
              ventas=ventas.generarVenta(ruts);
              for (int j = 0; j < (int) (Math.floor(Math.random()*3-0)+1); j++) {
                  int cantidad=0;
                  int id=(int)((Math.floor(Math.random() * (id_productos.size() - 0 + 0)) + 0));
                 productosVendidos= productosVendidos.generarProductosVendidos(ventas.getId_venta(),productosL.get(id).getId(),productosL.get(id).getPrecio());
                  ventas.setTotal( ventas.getTotal()+productosVendidos.getPrecio()*productosVendidos.getCantidad()); 
                 txtDatos.setText(txtDatos.getText()+"\n"+productosVendidos.toString());
            }
              
           
             
              txtDatos.setText(txtDatos.getText()+"\n"+ventas.toString());
        }
        }
        catch(Exception ex)
        {
            txtDatos.setText(txtDatos.getText()+"\n No existen usuarios o productos creados");
        }
        
    }//GEN-LAST:event_bntVentasActionPerformed

    private void btnGuardarScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarScriptActionPerformed
    BufferedReader in = new BufferedReader(new InputStreamReader(System.in)); 

    File file = new File("F:\\salida.txt"); 

    if (!file.exists()) { 
        try {
            if (file.createNewFile()) {
                jLabel2.setText("El fichero se ha creado correctamente");
            } else {
                
                 jLabel2.setText("No ha podido ser creado el fichero");
            }   } catch (IOException ex) { 
            Logger.getLogger(GeneradorDePoblacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 


    /*la clave de activar o no la sobreescritura esta en FileOutputStream(file, true) si le ponemos en true entonces agregas al final de la linea */ 

    BufferedWriter out = null; 
        try {
            out = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file, true), "UTF8"));
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GeneradorDePoblacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GeneradorDePoblacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            
            out.write(txtDatos.getText()); 
        } catch (IOException ex) {
            Logger.getLogger(GeneradorDePoblacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            out.close(); 
        } catch (IOException ex) {
            Logger.getLogger(GeneradorDePoblacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarScriptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneradorDePoblacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneradorDePoblacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneradorDePoblacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneradorDePoblacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneradorDePoblacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntVentas;
    private javax.swing.JButton btnGuardarScript;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDatos;
    // End of variables declaration//GEN-END:variables
}
